Features/resize oracle
raindrops-protocol/raindrops pull request #27
Opened 2022-08-11 00:33 UTC by staccDOTsol

For much larger games the authority (or permissionless) oracle may want to be resized.

@bhgames at your convenience this would help me with my hackathon submission :)

2022-08-11 00:35 UTC, staccDOTsol commented
in the case of https://hackblock.space:

if the authority can have an orderly object that includes many amounts from many players then the players themselves can take turns at concurrently paying out proceeds from previous rounds. It would also track who has entered when.

Cheers :)

2022-08-16 21:29 UTC, long-banana requested changes
Thanks for submitting this change.

Can you modify your approach to create a separate instruction to handle just resizing an oracle. Since the instruction already handles the ability to either create or update an oracle, adding the ability to also resize it is overloading this instruction with too many responsibilities.

2022-08-16 21:29 UTC, long-banana commented on js/cli/src/matches.ts
> +} from "../../lib/";
Switch this back to using the package

2022-08-16 21:29 UTC, long-banana commented on rust/matches/src/lib.rs
> +anchor_lang::declare_id!("9UPxDy3p6LjDck7LJAvCwqCXa8qUCG6oq2feuw7pgvH");
Switch this back to the original id

2022-08-16 21:29 UTC, long-banana commented on vanity.MD
> +hm
Remove

2022-08-16 21:29 UTC, long-banana commented on yarn.lock
>  # yarn lockfile v1
This PR shouldn't have any updates to the `yarn.lock` file

2022-08-16 21:29 UTC, long-banana commented on js/cli/yarn.lock
>    dependencies:
This PR shouldn't have any updates to the `yarn.lock` file

2022-08-16 21:38 UTC, staccDOTsol commented on rust/matches/src/lib.rs
> +anchor_lang::declare_id!("9UPxDy3p6LjDck7LJAvCwqCXa8qUCG6oq2feuw7pgvH");
duh lol

2022-08-16 23:55 UTC, staccDOTsol commented
what the fck yarn.lock

2022-08-17 00:03 UTC, staccDOTsol commented
closing in favor of https://github.com/raindrops-protocol/raindrops/pull/30

2022-08-17 00:03 UTC, closed without merging